# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: "Setup rcodesign"
author: "HashiCorp"
description: "Install rcodesign"

branding:
  color: "gray-dark"
  icon: "package"

inputs:
  github-token:
    description: "GitHub token for gh(1) to interact with GitHub API"
    required: true
  install-dir:
    description: "Where the tool will be installed; this directory will be added to GITHUB_PATH.  Default: ./.bob/tools"
  version:
    description: "Version of rcodesign to install"
    default: "0.22.0"

runs:
  using: composite
  steps:
    - name: Install rcodesign
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        DEST_DIR: ${{ inputs.install-dir }}
        VERSION: ${{ inputs.version }}
      run: |
        bash --version
        bash -x .github/scripts/install-rcodesign.sh
        echo "exit status $?"
        echo ==== after
        echo "$GITHUB_PATH"
        cat "$GITHUB_PATH"
        echo ====
    - name: Check New PATH
      shell: bash
      run: |
        set -x
        /usr/bin/env | grep '^PATH='
    - name: Run the tool
      shell: bash
      run: |
        rcodesign --version
    - name: Abort Abort Abort
      shell: bash
      run: |
        exit 1
